name: Publish to Registry

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  push:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
            name: laiello/youtube-dl-docker
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tag: "latest,${{ env.RELEASE_VERSION }}"
            tag_semver: true
